# Generated by Django 4.1 on 2024-02-03 22:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="eloHistory",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=[1200], size=None
            ),
        ),
    ]
